spring:
  security:
    user:
      name: user
      password: password
  # To fix this error: The bean 'methodSecurityInterceptor', defined in class path resource [org/activiti/spring/boot/MethodSecurityConfig.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/security/config/annotation/method/configuration/GlobalMethodSecurityConfiguration.class] and overriding is disabled.
  #main:
  #  allow-bean-definition-overriding: true

keycloak:
  jwtPublicKey: |
                  -----BEGIN PUBLIC KEY-----
                  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArB4vorj0v
                  b5GoY8+BHTswIpVTMyxPchj9FOhAzYapEaWK6tK34aa22vwwCOTP8
                  dF9mcGmdQCaMEa6AsAYhJ5nsNTEIINV0Zaqi2Sm4j8bUwPdJDqLJr
                  rlrFRHyPOW8peyX8xJUXaJdtPwaFKfmJlINFMlDW9gFbydahM+y32
                  WBldU2McPxW6RDGFCM/Q6rWufRAXX+97zN3jHZpOGdevJB0XgRlHD
                  VB2XmNz+z246G6IVLFhmnMxfWh86kfaiDFXbZcb3WTzcL6HrmZs4W
                  d5c+rseuzu8qW9cfPmF6e6uJGwHRlWNscLmifllVzlp6L2cYh3lom
                  sg/2fadRRP6dWowIDAQAB
                  -----END PUBLIC KEY-----
  audience: web_app
  serverUrl: https://keycloak.carbook-dev.gocarbook.com/auth
  realm: carbook
  clientId: ""
  clientSecret: ""
  userName: ""
  password: ""
