spring:
  application:
    name: tinyerp
  output:
    ansi:
      enabled: always
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

logging:
  level:
    org:
      zalando:
        logbook: TRACE

gateway:
  keycloak:
    jwtPublicKey: |
                    -----BEGIN PUBLIC KEY-----
                    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiv4c6oSQtvGmP++/xBBek/k+F0mUvwIpiMZ7qyfWHo5RaImoCo7ZMhQfxaY4fFcKX1xiS7Qk3+CaXZTyC4BHq4PAV5hokH5l06TrMtKM85RdFTTT44eEfFPTkl+SFCYCR5HgQ6/NsaZVUcIl8I0mog/k9bVzKgQZtt5XXbBtWrBJCehezPOMxVIRoaSfrN7Qyd/1EaGXc7sij1WnFz9UxS0KaTuS8yvWT3R4W4tkl3clqAg1eKNx96E3jS3b77H/JQhoPbBzzopNOuzik5XXAca3u01boU01zTp7PYuuV6xhMxYL8Pv48li6L7nG1ST2Ry+5vPW5pKXqTn371A1ZBwIDAQAB
                    -----END PUBLIC KEY-----
    serverUrl: https://keycloak.carbook-dev.gocarbook.com/auth
    realm: tinyerp-dev
    clientId: web-app